spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/shortener
    password: '1234'
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER